exports.plans = [
  {sku: "F1", name: "Free", price: 0.00, cores: "Shared", ram: "1G", storage: "1g", description: "The Free and Shared (preview) service plans are base tiers that run on the same Azure VMs as other apps. Some apps may belong to other customers. These tiers are intended to be used only for development and testing purposes. There is no SLA provided for Free and Shared service plans. Free and Shared plans are metered on a per App basis."},
  {sku: "B1", name: "Basic 1", price: 54.75, cores: "1", ram: "1.75G", storage: "1g", description: "The Basic service plan is designed for apps that have lower traffic requirements, and don't need advanced auto scale and traffic management features. Pricing is based on the size and number of instances you run. Built-in network load balancing support automatically distributes traffic across instances. The Basic service plan with Linux runtime environments supports Web App for Containers"},
  {sku: "B2", name: "Basic 2", price: 109.50, cores: "2", ram: "3.50G", storage: "10g", description: "The Basic service plan is designed for apps that have lower traffic requirements, and don't need advanced auto scale and traffic management features. Pricing is based on the size and number of instances you run. Built-in network load balancing support automatically distributes traffic across instances. The Basic service plan with Linux runtime environments supports Web App for Containers"},
  {sku: "B3", name: "Basic 3", price: 219.00, cores: "4", ram: "7G", storage: "10g", description: "The Basic service plan is designed for apps that have lower traffic requirements, and don't need advanced auto scale and traffic management features. Pricing is based on the size and number of instances you run. Built-in network load balancing support automatically distributes traffic across instances. The Basic service plan with Linux runtime environments supports Web App for Containers"},
  {sku: "S1", name: "Standard 1", price: 73.00, cores: "1", ram: "1.75G", storage: "50g", description: "The Standard service plan is designed for running production workloads. Pricing is based on the size and number of instances you run. Built-in network load balancing support automatically distributes traffic across instances. The Standard plan includes auto scale that can automatically adjust the number of virtual machine instances running to match your traffic needs."},
  {sku: "S2", name: "Standard 2", price: 146.00, cores: "2", ram: "3.50G", storage: "50g", description: "The Standard service plan is designed for running production workloads. Pricing is based on the size and number of instances you run. Built-in network load balancing support automatically distributes traffic across instances. The Standard plan includes auto scale that can automatically adjust the number of virtual machine instances running to match your traffic needs."},
  {sku: "S3", name: "Standard 3", price: 292.00, cores: "4", ram: "7G", storage: "50g", description: "The Standard service plan is designed for running production workloads. Pricing is based on the size and number of instances you run. Built-in network load balancing support automatically distributes traffic across instances. The Standard plan includes auto scale that can automatically adjust the number of virtual machine instances running to match your traffic needs."},
  {sku: "P1v2", name: "Premium v1", price: 146.00, cores: "1", ram: "3.5G", storage: "250G", description: "The Premium service plan is designed to provide enhanced performance for production apps. The upgraded Premium plan, Premium v2, features Dv2-series VMs with faster processors, SSD storage, and double memory-to-core ratio compared to Standard. The new Premium plan also supports higher scale via increased instance count while still providing all the advanced capabilities found in the Standard plan."},
  { sku: "P2v2", name: "Premium v2", price: 292.00, cores: "2", ram: "7G", storage: "250G", description: "The Premium service plan is designed to provide enhanced performance for production apps. The upgraded Premium plan, Premium v2, features Dv2-series VMs with faster processors, SSD storage, and double memory-to-core ratio compared to Standard. The new Premium plan also supports higher scale via increased instance count while still providing all the advanced capabilities found in the Standard plan."},
  { sku: "P3v2", name: "Premium v3", price: 584.00, cores: "4", ram: "14G", storage: "250G", description: "The Premium service plan is designed to provide enhanced performance for production apps. The upgraded Premium plan, Premium v2, features Dv2-series VMs with faster processors, SSD storage, and double memory-to-core ratio compared to Standard. The new Premium plan also supports higher scale via increased instance count while still providing all the advanced capabilities found in the Standard plan."}
];

exports.dbs = [ 
  {sku: "B_Gen5_1", name: "Basic Compute 1", cores: 1, ram: 2, price: 33.00, description: "Workloads requiring light compute and I/O performance."},
  {sku: "B_Gen5_2", name: "Basic Compute 2", cores: 2, ram: 4, price: 65.00, description: "Workloads requiring light compute and I/O performance."},
  {sku: "GP_Gen5_2", name: "General Purpose 2", cores: 2, ram: 10, price: 103.00, description: "Most business workloads requiring balanced compute and memory with scalable I/O throughput."},
  {sku: "GP_Gen5_4", name: "General Purpose 4", cores: 4, ram: 20, price: 206.00, description: "Most business workloads requiring balanced compute and memory with scalable I/O throughput."},
  {sku: "GP_Gen5_8", name: "General Purpose 8", cores: 8, ram: 40, price: 412.00, description: "Most business workloads requiring balanced compute and memory with scalable I/O throughput."},
  {sku: "GP_Gen5_16", name: "General Purpose 16", cores: 16, ram: 80, price: 824.00, description: "Most business workloads requiring balanced compute and memory with scalable I/O throughput."},
  {sku: "GP_Gen5_32", name: "General Purpose 32", cores: 32, ram: 160, price: 1648.00, description: "Most business workloads requiring balanced compute and memory with scalable I/O throughput."},
  {sku: "GP_Gen5_64", name: "General Purpose 64", cores: 64, ram: 320, price: 3300.00, description: "Most business workloads requiring balanced compute and memory with scalable I/O throughput."},
  {sku: "MO_Gen5_4", name: "Memory Optimized 4", cores: 4, ram: 40, price: 256.00, description: "High performance database workloads requiring in-memory performance for faster transaction processing and higher concurrency."},
  { sku: "MO_Gen5_8", name: "Memory Optimized 8", cores: 8, ram: 80, price: 512.00, description: "High performance database workloads requiring in-memory performance for faster transaction processing and higher concurrency."},
  { sku: "MO_Gen5_16", name: "Memory Optimized 16", cores: 16, ram: 160, price: 1025.00, description: "High performance database workloads requiring in-memory performance for faster transaction processing and higher concurrency."},
  { sku: "MO_Gen5_32", name: "Memory Optimized 32", cores: 32, ram: 320, price: 2050.00, description: "High performance database workloads requiring in-memory performance for faster transaction processing and higher concurrency."}
]

